#Normal Imports

In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import pandas as pd
import time

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [3]:
%%time
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()
zeros

CPU times: total: 0 ns
Wall time: 14.1 ms


tensor([[0.]])

In [8]:
%%time
start_time_np = time.time()
zeros_np = np.zeros(1)
end_time_np = time.time()
zeros_np

CPU times: total: 0 ns
Wall time: 50.3 μs


array([0.])

In [10]:
elapsed_time = end_time - start_time
elapsed_time_np = end_time_np - start_time_np
print(f"Time for the tensor array : {elapsed_time} \nTime for the numpy array : {elapsed_time_np}")

Time for the tensor array : 0.013962268829345703 
Time for the numpy array : 1.3589859008789062e-05


In [31]:
#np.dot is torch.matmul is the dot product for this
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time =time.time()

rand = torch.matmul(torch_rand1, torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
elapsed_time


0.21921229362487793

In [34]:
# use batch matrix multiplication (np.matmul) instead of np.dot to avoid creating a huge 6-D result
start_time = time.time()

rand_np = np.matmul(np_rand1, np_rand2)

end_time = time.time()

elapsed_time_np = end_time - start_time
elapsed_time_np

C:\Users\Jeevant\AppData\Local\Temp\ipykernel_7404\2058661127.py:4: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand_np = np.matmul(np_rand1, np_rand2)


0.7591400146484375

In [35]:
#embeddings :
# torch.stack, torch.matmul, torch.multinomial, torch.tril, torch.triu, torch.T / torch.transpose, nn.Linear, torch.cat, F.softmax ........
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probablitites points to the index of the probabilities in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial( probabilities, num_samples=10, replacement=True)
print(samples)


tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [41]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
print(out)

tensor([1, 2, 3, 4, 5])


In [40]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=-1)
print(out)

tensor([1, 2, 3, 4, 5])


In [42]:
trilower = torch.tril(torch.ones(5,5))
trilower

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [43]:
triupper = torch.triu(torch.ones(5,5))
triupper

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [44]:
matriu = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
matriu

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [45]:
exp = torch.exp(matriu)
exp

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [49]:
input = torch.zeros(2,3,4)
out1 = input.transpose(0,1)
out2 = input.transpose(-2 , 1)
print(out1.shape)
print(out2.shape)

torch.Size([3, 2, 4])
torch.Size([2, 3, 4])


In [50]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

#Stacked them along a new dimension

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 4.0675,  6.2880, -0.0310], grad_fn=<SqueezeBackward4>)


In [ ]:
import torch.nn.functional as F

#create a tensor 
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Applying softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [54]:
#Initialize an embedding vector
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

#Creating some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#Apply the embedding layer
embedding_output = embedding(input_indices)

#The output will be tensor of shape (4, 100) , where 4 is the number of inputs
#and 100 is the dimensity of the embedding vectors
print(embedding_output.shape)
print(embedding_output)

torch.Size([4, 6])
tensor([[ 0.8353,  0.8121,  1.1494,  0.7898,  0.1033, -0.9996],
        [ 0.9524, -1.6162, -2.1571,  1.0031, -1.3561, -2.3615],
        [-0.7449,  1.7632, -0.4562,  0.2634,  0.0196,  0.5773],
        [-0.7251,  0.5334,  1.0859, -1.1395, -0.8588, -3.0383]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
#print(a@b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [58]:
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
int_64 = torch.randint(1, (3, 2)).float
#type int64
float_32 = torch.rand(2, 3)
#type float32
print(int_64.dtype(), float_32.dtype())
result = torch.matmul(int_64, float_32)
print(result)

AttributeError: 'builtin_function_or_method' object has no attribute 'dtype'

In [79]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y , z = a. shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [80]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
#print(input)
print(output[:, -1:])

tensor([[7.1448e-01, 1.8475e-01, 2.0102e-01, 4.0570e-01, 8.8612e-01, 2.0743e-01,
         5.1077e-01, 3.7298e-01, 8.0850e-01, 5.2007e-01],
        [7.8412e-01, 2.6118e-01, 3.7562e-01, 7.8262e-01, 5.1823e-01, 3.5013e-01,
         9.5245e-01, 3.8758e-01, 9.4915e-02, 9.5855e-01],
        [5.7510e-01, 7.1145e-01, 4.3427e-01, 1.7449e-01, 7.1777e-01, 4.5878e-01,
         8.5748e-01, 1.7953e-02, 2.0927e-01, 1.7103e-01],
        [5.5305e-01, 6.6860e-02, 8.9135e-01, 9.2828e-01, 2.2116e-01, 7.0217e-01,
         5.9173e-01, 8.7067e-01, 6.7164e-01, 1.4756e-01],
        [1.9641e-01, 3.9470e-01, 2.3279e-01, 1.7805e-01, 7.4658e-01, 3.0232e-01,
         2.1327e-01, 2.4263e-01, 7.0642e-01, 8.5303e-01],
        [3.3284e-01, 1.8608e-01, 5.9807e-01, 1.1039e-01, 1.1520e-01, 9.7908e-01,
         7.6473e-01, 1.0472e-01, 5.7270e-01, 5.3800e-01],
        [2.7408e-01, 4.5747e-01, 2.9135e-01, 1.8731e-01, 8.9197e-01, 7.4070e-01,
         4.3595e-01, 8.2271e-01, 8.2310e-01, 2.5314e-01],
        [5.3810e-01, 3.9609

In [81]:
x = torch.tensor([10], dtype=torch.float32)
y =  F.tanh(x)
print(y)

tensor([1.])
